#!/bin/bash

# Reads geometries.xyz from several directories generated by NX-NS and uses nx-distance.py to plot the 
# distances between two atoms, and generates a html table at the end.
# The user should provide a file containing the name of the directories in a single column, and the scripts
# assumes $DIRECTORY/RESULTS/geometries.xyz .
#
#
# Usage: bash run_all_bondlengths.sh dir_list.txt atom1 atom2 trajectory_filename
# Example: bash run_all_bondlengths.sh dir_list.txt 17 25 trajectory.txt
#
# M. Casal - 16/10/2025

#!/bin/bash
# Usage: bash run_all_bondlengths.sh dir_list.txt atom1 atom2 [plot_script] [trajectory_file]

workdir=$(pwd)
listfile=$1
atom1=$2
atom2=$3
plot_script=${4:-"/Users/mrncasal/compchem/nx-distance.py"}
trajfile=${5:-geometries.xyz}
output_html="distance-${atom1}-${atom2}-plots.html"

# Create or reset HTML file
echo "<html><head><title>Distance ${atom1} - ${atom2}</title></head><body>" > "$output_html"
echo "<h1>Bond length plots summary (atoms ${atom1}-${atom2})</h1><table border='1' cellspacing='10'>" >> "$output_html"

while read -r job; do
    if [ -d "$job" ]; then
        echo "Processing directory: $job"
        dir="$job/RESULTS/"
        cd "$dir" || continue
        echo "Now in $(pwd)"

        if [ -f "$trajfile" ]; then
            python "$plot_script" "$trajfile" "$atom1" "$atom2"

            if [ -f distance_plot.png ]; then
                plotname="bond_${atom1}_${atom2}.png"
                mv distance_plot.png "$plotname"
                echo "Created $plotname"
            else
                echo " No plot generated in $dir"
            fi
        else
            echo " No trajectory file found: $trajfile"
        fi

        cd "$workdir"

        # Add the image to HTML if it exists
        if [ -f "$dir/bond_${atom1}_${atom2}.png" ]; then
            echo "<tr><td><b>${dir}</b></td><td><img src=\"${dir}/bond_${atom1}_${atom2}.png\" width=\"400\"></td></tr>" >> "$output_html"
        else
            echo "<tr><td><b>${dir}</b></td><td><i>No plot found</i></td></tr>" >> "$output_html"
        fi
    else
        echo "Skipping missing directory: $job"
    fi
done < "$listfile"

echo "</table></body></html>" >> "$output_html"
echo " Done! Open $output_html to view all bond length plots."


