#!/bin/bash

#SBATCH --cluster=wice
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1        # CREST is OpenMP, not MPI
#SBATCH --cpus-per-task=10         # use this for OMP threads
#SBATCH --time=2-23:00:00
#SBATCH --job-name=crest
#SBATCH -o crest.stdout
#SBATCH --partition=batch_sapphirerapids
#SBATCH -A lcomputational_photochemistry
#SBATCH --mem-per-cpu=4000M

molecule=Endo-D1
workdir=/data/leuven/353/vsc35379/ml-mrtadf/data/y-batch1/$molecule/crest

module load cluster/wice/batch_icelake
module load CREST/2.12-intel-2021a
module load xtb/6.6.1-intel-2021a

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OMP_STACKSIZE=1000m
export OPENBLAS_NUM_THREADS=1
ulimit -s unlimited

cd $workdir

xtb $molecule.xyz --opt tight --gfn2  > $workdir/xtb.out 
crest xtbopt.xyz --gfn2 --gbsa toluene -T 10  -ewin 0.6 -rthr 5. > $workdir/crest.out
