#!/bin/bash

input=$1
name=${input%.com}
indir=`pwd`
output=$name.log
chk=$name.chk
error=$name.err

#
# Making an input-file for submitting
#

cat <<EOJ >$name.slurm
#!/bin/bash
#SBATCH --cluster=wice
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36
#SBATCH --time=6-23:59:00
#SBATCH --job-name=$name
#SBATCH -o $name.stdout
#SBATCH -A lcomputational_photochemistry
#SBATCH --partition=batch_long

# some comments on input:  --cluster=wice  --> uses wice cluster ( wice or genius are the current Tier-2 clusters)
# some comments on input:  --nodes sets the amount of nodes,  for gaussian you should never take more than 1 node: we don't have the license
# some comments on input:  --nodes continued: to do multi-node calculations anyway (because it wasn't efficient, according to Hans)
# some comments on input:  --nodes continued: node availability (~10 / cluster (genius/wice)) requesting a high amount of nodes will make it harder to start
# some comments on input:  --ntasks-per-node   36 max on genius, 72 max on wice
# some comments on input:  --time  uses format  days-hours:minutes:seconds  (f.e.  2-10:15:45)
# some comments on input:  --partition  'batch_long' long jobs (> 3 days),  long is in principle 3-7 days
# some comments on input:  --partition  continued:  'bigmem' high memory (2048 GB RAM / node), 28000MB/core max (wice), (768 GB RAM/node ) (genius) 
# some comments on input:  --partition  continued:  'gpu' GPU nodes (per GPU request 18 cores), --gpus-per-node=3 --ntasks=54
# also interactinve partition (wice): ' srun -n 1 -t 01:00:00 -A lcomputational_photochemistry --partition=interactive --cluster=wice --pty bash -l'
#  has 16h max walltime  (example 1h walltime),  can ask for GPU  (requires also   --ntasks-per-node=8 --gpus-per-node=1 --x11 ) 1 GPU max
# some comments on input:  wice tips see also https://docs.vscentrum.be/en/latest/leuven/wice_quick_start.html?highlight=wice
# some comments on input: --job-name  job-name (to see in squeue)
# some comments on input: -o   outputlog  (+ errors)
# some comments on input: -A account to use credits from (check with 'sam-balance' )
# some comments on input: --mem-per-cpu=3400M is about limit for 'thin' nodes on wice (~250 Gb/n),  use --partition bigmem for bigger jobs, there limit is 28000M (~2 Tb/n)
# some comments on input: --mem-per-cpu=5000M is about limit for 'thin' nodes on genius (~180 Gb/n),  use --partition bigmem for bigger jobs, there limit is ~21000M (~750 Gb/n)
# 

export g16root=/data/leuven/301/vsc30101/g16A03
. \$g16root/bsd/g16.profile

mkdir -p $VSC_SCRATCH/\$SLURM_JOB_ID

cd $VSC_SCRATCH/\$SLURM_JOB_ID
cp $indir/$input .
g16 < $input > $output 2> $error

rsync * $indir/
#rm -f $input

exit 0

EOJ

#
#   submitting the inputfile created above
#

sbatch $name.slurm

rm -f $name.slurm

exit 0
